---
- hosts: all
  become: true
  tasks:
    - name: Install Apache HTTP Server
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/yalla/Desktop/devops/ansible/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
